ALTER TABLE "User" ADD COLUMN "canUploadFiles" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canCreateFolders" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canCreateNotes" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canCreateReminders" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canCreateDocumentRecords" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canViewAnnouncements" BOOLEAN NOT NULL DEFAULT true;
